# Use the official Jupyter Notebook image
FROM jupyter/base-notebook:latest

# Install any additional packages you need
# RUN pip install --no-cache-dir <your-packages>

# Set the working directory
WORKDIR /home/jovyan/work
